class ExpectedException(Exception):
    pass


class UnexpectedException(Exception):
    pass
